[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
potter_potter = "A3jca3XyW52j1aMdpE75affvCtgyN4UwNc1Sn2ahLzo6"

[programs.localnet]
potter_potter = "A3jca3XyW52j1aMdpE75affvCtgyN4UwNc1Sn2ahLzo6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/solflare-devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
